name: build

on:
  workflow_dispatch:
  push:
      branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 2 * * 0'

env:
  DOTNET_NOLOGO: true
  MAILBLUSTER_API_KEY: ${{ secrets.MAILBLUSTER_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Setup dotnet 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release
          /p:CollectCoverage=true
          /p:CoverletOutputFormat="\"cobertura,json\""
          /p:CoverletOutput=coverage/
          /p:IncludeTestAssembly=false
          /p:ExcludeByAttribute="System.CodeDom.Compiler.GeneratedCodeAttribute"
      - name: Upload dotnet test results
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/src/Sidio.MailBluster.Tests/coverage/coverage.net8.0.cobertura.xml ${{ github.workspace }}/src/Sidio.MailBluster.Tests/coverage/coverage.net9.0.cobertura.xml
          format: cobertura
        if: ${{ always() }}